[package]
name = "project-zyheeda-pathfinding"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.0", features = ["dynamic_linking", "file_watcher"] }
serde = "1.0.215"
serde_json = "1.0.133"
uuid = "1.11.0"
